import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from "@/components/theme-provider"

import { cn } from "@/lib/utils";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning className="scroll-smooth focus:scroll-auto">
      <body className={cn("bg-secondary",inter.className)}>
        <ThemeProvider  attribute="class" defaultTheme="system" enableSystem>
        {children}
        <Toaster />
        </ThemeProvider>
        </body>
    </html>
    </ClerkProvider>
  );
}
